// Mock Data for LKP Parduli Rasa Komputer

export const courses = [
  {
    id: 1,
    title: 'Aplikasi Microsoft Word',
    aliases: ['Microsoft Word', 'MS Word', 'Word'],
    description: 'Pelajari pengolahan dokumen profesional dengan Microsoft Word, mulai dari dasar hingga mahir.',
    icon: 'FileText',
    price: 'Rp 500.000',
    duration: '3 Bulan',
    level: 'Dasar - Menengah',
    materials: ['Pengenalan MS Word', 'Formatting Dokumen', 'Tabel & Grafik', 'Mail Merge', 'Cetak Massal']
  },
  {
    id: 2,
    title: 'Aplikasi Microsoft Excel',
    aliases: ['Microsoft Excel', 'MS Excel', 'Excel'],
    description: 'Kuasai pengolahan data, rumus, dan visualisasi data menggunakan Microsoft Excel.',
    icon: 'Table',
    price: 'Rp 550.000',
    duration: '3 Bulan',
    level: 'Dasar - Lanjutan',
    materials: ['Pengenalan MS Excel', 'Rumus & Fungsi', 'Pivot Table', 'Chart & Grafik', 'Macro Dasar']
  },
  {
    id: 3,
    title: 'Aplikasi Microsoft PowerPoint',
    aliases: ['Microsoft PowerPoint', 'PowerPoint', 'PPT'],
    description: 'Buat presentasi yang menarik dan profesional dengan Microsoft PowerPoint.',
    icon: 'Presentation',
    price: 'Rp 450.000',
    duration: '2 Bulan',
    level: 'Dasar - Menengah',
    materials: ['Pengenalan Slide', 'Desain Template', 'Animasi & Transisi', 'Multimedia', 'Tips Presentasi']
  },
  {
    id: 4,
    title: 'Desain Grafis Adobe Photoshop',
    aliases: ['Adobe Photoshop', 'Photoshop'],
    description: 'Pelajari editing foto dan desain grafis profesional menggunakan Adobe Photoshop.',
    icon: 'Image',
    price: 'Rp 750.000',
    duration: '4 Bulan',
    level: 'Menengah - Lanjutan',
    materials: ['Pengenalan Photoshop', 'Layer & Masking', 'Retouching Foto', 'Desain Poster', 'Manipulasi Gambar']
  },
  {
    id: 5,
    title: 'Aplikasi Corel Draw',
    aliases: ['Corel Draw', 'CorelDraw'],
    description: 'Kuasai desain vektor dan layout profesional dengan CorelDraw untuk kebutuhan percetakan.',
    icon: 'Palette',
    price: 'Rp 700.000',
    duration: '4 Bulan',
    level: 'Menengah - Lanjutan',
    materials: ['Pengenalan CorelDraw', 'Desain Logo', 'Layout Brosur', 'Desain Kemasan', 'Cetak & Export']
  },
  {
    id: 6,
    title: 'Aplikasi Auto CAD',
    aliases: ['Auto CAD', 'AutoCAD'],
    description: 'Belajar gambar teknik dan desain arsitektur menggunakan AutoCAD secara profesional.',
    icon: 'PenTool',
    price: 'Rp 850.000',
    duration: '5 Bulan',
    level: 'Menengah - Lanjutan',
    materials: ['Pengenalan AutoCAD', 'Gambar 2D', 'Gambar 3D', 'Layout & Plotting', 'Proyek Akhir']
  }
];

export const blogPosts = [
  {
    id: 1,
    title: 'Pentingnya Keterampilan Komputer di Era Digital',
    summary: 'Di era digital ini, keterampilan mengoperasikan komputer menjadi kebutuhan dasar yang tidak bisa diabaikan.',
    content: 'Di era digital seperti sekarang ini, kemampuan mengoperasikan komputer bukan lagi sekadar keahlian tambahan, melainkan sudah menjadi kebutuhan pokok. Hampir semua sektor pekerjaan kini membutuhkan kemampuan dasar komputer, mulai dari administrasi perkantoran, desain grafis, hingga teknik sipil. LKP Parduli Rasa hadir untuk menjawab kebutuhan tersebut dengan menyediakan program-program kursus yang beragam dan terjangkau. Dengan didukung oleh pengajar yang berpengalaman dan kurikulum yang terus diperbarui, kami berkomitmen untuk mencetak lulusan yang siap bersaing di dunia kerja.',
    image: null,
    author: 'Admin LKP',
    date: '2026-03-15',
    category: 'Edukasi'
  },
  {
    id: 2,
    title: 'Pelatihan Excel untuk Meningkatkan Produktivitas Kerja',
    summary: 'Microsoft Excel adalah alat yang sangat powerful untuk mengolah data dan meningkatkan efisiensi kerja sehari-hari.',
    content: 'Microsoft Excel telah menjadi standar industri untuk pengolahan data dan analisis bisnis. Dengan menguasai Excel, Anda dapat mengotomatisasi tugas-tugas yang berulang, membuat laporan yang informatif, dan mengambil keputusan berbasis data. Kursus Excel di LKP Parduli Rasa dirancang untuk memberikan pemahaman mendalam mulai dari fungsi dasar seperti SUM dan AVERAGE, hingga fitur lanjutan seperti Pivot Table, VLOOKUP, dan Macro. Siswa juga akan mendapatkan studi kasus nyata yang dapat langsung diterapkan di tempat kerja.',
    image: null,
    author: 'Admin LKP',
    date: '2026-03-10',
    category: 'Tips & Trik'
  },
  {
    id: 3,
    title: 'LKP Parduli Rasa Sukses Gelar Workshop Desain Grafis',
    summary: 'Workshop desain grafis yang diadakan oleh LKP Parduli Rasa berhasil menarik peserta dari berbagai kalangan.',
    content: 'LKP Parduli Rasa baru saja menyelenggarakan workshop desain grafis yang dihadiri oleh lebih dari 50 peserta. Workshop ini membahas dasar-dasar desain menggunakan Adobe Photoshop dan CorelDraw. Para peserta sangat antusias mengikuti sesi praktik langsung yang dibimbing oleh instruktur berpengalaman. Kegiatan ini merupakan bagian dari program pengabdian masyarakat LKP Parduli Rasa untuk meningkatkan keterampilan digital masyarakat.',
    image: null,
    author: 'Admin LKP',
    date: '2026-03-05',
    category: 'Kegiatan'
  },
  {
    id: 4,
    title: 'Tips Membuat Presentasi yang Menarik dan Profesional',
    summary: 'Pelajari cara membuat presentasi PowerPoint yang memikat audiens dan menyampaikan pesan dengan efektif.',
    content: 'Membuat presentasi yang baik bukan hanya soal mengisi slide dengan teks. Diperlukan pemahaman tentang prinsip desain, pemilihan warna, penggunaan gambar, serta teknik storytelling yang baik. Di kursus PowerPoint kami, siswa akan belajar bagaimana merancang slide yang bersih, modern, dan profesional. Kami juga mengajarkan teknik animasi dan transisi yang tepat agar presentasi lebih dinamis tanpa berlebihan.',
    image: null,
    author: 'Admin LKP',
    date: '2026-02-28',
    category: 'Tips & Trik'
  }
];

export const students = [
  { id: 1, nis: 'PRK-2026-001', name: 'Ahmad Fauzi', program: 'Microsoft Word', courseId: 1, enrollmentId: 'enr-2026-001', accountId: 'acc-student-ahmad', status: 'Aktif', email: 'ahmad@email.com', phone: '081234567890', address: 'Jl. Merdeka No. 10', paymentStatus: 'verified', paymentDate: '2026-01-10', registrationDate: '2026-01-05' },
  { id: 2, nis: 'PRK-2026-002', name: 'Siti Nurhaliza', program: 'Microsoft Excel', courseId: 2, enrollmentId: 'enr-2026-002', accountId: 'acc-student-siti', status: 'Aktif', email: 'siti@email.com', phone: '081234567891', address: 'Jl. Sudirman No. 25', paymentStatus: 'verified', paymentDate: '2026-01-15', registrationDate: '2026-01-12' },
  { id: 3, nis: 'PRK-2026-003', name: 'Budi Santoso', program: 'Adobe Photoshop', courseId: 4, enrollmentId: 'enr-2025-003', accountId: 'acc-student-budi', status: 'Lulus', email: 'budi@email.com', phone: '081234567892', address: 'Jl. Gatot Subroto No. 5', paymentStatus: 'verified', paymentDate: '2025-09-10', registrationDate: '2025-09-01' },
  { id: 4, nis: 'PRK-2026-004', name: 'Dewi Lestari', program: 'Corel Draw', courseId: 5, enrollmentId: 'enr-2026-004', accountId: 'acc-student-dewi', status: 'Aktif', email: 'dewi@email.com', phone: '081234567893', address: 'Jl. Ahmad Yani No. 15', paymentStatus: 'pending', paymentDate: null, registrationDate: '2026-03-01' },
  { id: 5, nis: 'PRK-2026-005', name: 'Rudi Hermawan', program: 'Auto CAD', courseId: 6, enrollmentId: 'enr-2026-005', accountId: 'acc-student-rudi', status: 'Aktif', email: 'rudi@email.com', phone: '081234567894', address: 'Jl. Diponegoro No. 30', paymentStatus: 'pending', paymentDate: null, registrationDate: '2026-03-05' },
  { id: 6, nis: 'PRK-2026-006', name: 'Fitri Handayani', program: 'Microsoft PowerPoint', courseId: 3, enrollmentId: 'enr-2025-006', accountId: 'acc-student-fitri', status: 'Lulus', email: 'fitri@email.com', phone: '081234567895', address: 'Jl. Imam Bonjol No. 8', paymentStatus: 'verified', paymentDate: '2025-08-20', registrationDate: '2025-08-15' },
  { id: 7, nis: 'PRK-2026-007', name: 'Andi Prasetyo', program: 'Microsoft Word', courseId: 1, enrollmentId: 'enr-2026-007', accountId: 'acc-student-andi', status: 'Aktif', email: 'andi@email.com', phone: '081234567896', address: 'Jl. Veteran No. 12', paymentStatus: 'rejected', paymentDate: null, registrationDate: '2026-03-10' },
  { id: 8, nis: 'PRK-2026-008', name: 'Maya Sari', program: 'Adobe Photoshop', courseId: 4, enrollmentId: 'enr-2026-008', accountId: 'acc-student-maya', status: 'Aktif', email: 'maya@email.com', phone: '081234567897', address: 'Jl. Kartini No. 20', paymentStatus: 'verified', paymentDate: '2026-02-14', registrationDate: '2026-02-10' },
];

export const galleryItems = [
  { id: 1, title: 'Kelas Microsoft Word', description: 'Suasana belajar di kelas Microsoft Word bersama instruktur', type: 'photo', image: null },
  { id: 2, title: 'Workshop Desain Grafis', description: 'Peserta antusias mengikuti workshop desain grafis', type: 'photo', image: null },
  { id: 3, title: 'Ujian Praktik AutoCAD', description: 'Siswa sedang mengerjakan ujian praktik AutoCAD', type: 'photo', image: null },
  { id: 4, title: 'Wisuda Siswa 2025', description: 'Perayaan wisuda angkatan 2025 LKP Parduli Rasa', type: 'photo', image: null },
  { id: 5, title: 'Lab Komputer', description: 'Fasilitas laboratorium komputer yang modern dan nyaman', type: 'photo', image: null },
  { id: 6, title: 'Kegiatan Sertifikasi', description: 'Proses sertifikasi kompetensi bagi siswa yang telah lulus', type: 'photo', image: null },
];

export const contactMessages = [
  { id: 1, name: 'Rina Wati', email: 'rina@email.com', address: 'Jl. Kenanga No. 5', message: 'Apakah ada jadwal kursus untuk kelas malam?', date: '2026-03-15', status: 'unread', response: '' },
  { id: 2, name: 'Doni Setiawan', email: 'doni@email.com', address: 'Jl. Mawar No. 8', message: 'Berapa biaya untuk kursus paket lengkap Microsoft Office?', date: '2026-03-14', status: 'replied', response: 'Untuk paket lengkap Microsoft Office (Word, Excel, PowerPoint) harganya Rp 1.350.000. Silakan datang langsung untuk pendaftaran.' },
  { id: 3, name: 'Lisa Permata', email: 'lisa@email.com', address: 'Jl. Melati No. 12', message: 'Apakah tersedia kelas online?', date: '2026-03-12', status: 'unread', response: '' },
];

export const studentMessages = [
  {
    id: 1,
    studentId: 1,
    enrollmentId: 'enr-2026-001',
    courseId: 1,
    studentName: 'Ahmad Fauzi',
    subject: 'Jadwal Kelas',
    message: 'Pak, apakah jadwal kelas Word minggu depan tetap seperti biasa?',
    date: '2026-03-16',
    status: 'unread',
    response: '',
    messages: [
      {
        id: 'thread-1-message-1',
        authorRole: 'student',
        authorName: 'Ahmad Fauzi',
        body: 'Pak, apakah jadwal kelas Word minggu depan tetap seperti biasa?',
        createdAt: '2026-03-16T08:00:00.000Z',
      },
    ],
  },
  {
    id: 2,
    studentId: 2,
    enrollmentId: 'enr-2026-002',
    courseId: 2,
    studentName: 'Siti Nurhaliza',
    subject: 'Materi Tambahan',
    message: 'Bu, boleh minta materi tambahan tentang Pivot Table?',
    date: '2026-03-15',
    status: 'replied',
    response: 'Tentu, silahkan unduh materi tambahan di menu Materi Kursus ya.',
    messages: [
      {
        id: 'thread-2-message-1',
        authorRole: 'student',
        authorName: 'Siti Nurhaliza',
        body: 'Bu, boleh minta materi tambahan tentang Pivot Table?',
        createdAt: '2026-03-15T09:15:00.000Z',
      },
      {
        id: 'thread-2-message-2',
        authorRole: 'admin',
        authorName: 'Admin LKP',
        body: 'Tentu, silahkan unduh materi tambahan di menu Materi Kursus ya.',
        createdAt: '2026-03-15T12:00:00.000Z',
      },
    ],
  },
  {
    id: 3,
    studentId: 4,
    enrollmentId: 'enr-2026-004',
    courseId: 5,
    studentName: 'Dewi Lestari',
    subject: 'Sertifikat',
    message: 'Kapan sertifikat saya bisa diunduh?',
    date: '2026-03-14',
    status: 'unread',
    response: '',
    messages: [
      {
        id: 'thread-3-message-1',
        authorRole: 'student',
        authorName: 'Dewi Lestari',
        body: 'Kapan sertifikat saya bisa diunduh?',
        createdAt: '2026-03-14T10:30:00.000Z',
      },
    ],
  },
];

export const certificates = [
  { id: 1, studentId: 3, enrollmentId: 'enr-2025-003', courseId: 4, nis: 'PRK-2026-003', studentName: 'Budi Santoso', program: 'Adobe Photoshop', issueDate: '2026-02-28', status: 'available' },
  { id: 2, studentId: 6, enrollmentId: 'enr-2025-006', courseId: 3, nis: 'PRK-2026-006', studentName: 'Fitri Handayani', program: 'Microsoft PowerPoint', issueDate: '2026-03-01', status: 'available' },
];

export const accreditations = [
  {
    id: 1,
    title: 'Akreditasi BAN-PNF LKP Parduli Rasa',
    certificateNumber: 'BAN-PNF/LKP-PR/2024/001',
    description: 'Dokumen akreditasi lembaga kursus komputer dari BAN-PNF sebagai bukti mutu layanan pelatihan LKP Parduli Rasa.',
    expiryDate: '2028-12-31',
    year: '2028',
    status: 'Aktif',
    documentUrl: '',
    documentName: '',
    document: null,
  },
  {
    id: 2,
    title: 'Perpanjangan Akreditasi Program Kursus Komputer',
    certificateNumber: 'AKR-PROG/LKP-PR/2025/014',
    description: 'Dokumen perpanjangan akreditasi untuk program pelatihan komputer yang diselenggarakan oleh LKP Parduli Rasa.',
    expiryDate: '2029-06-30',
    year: '2029',
    status: 'Aktif',
    documentUrl: '',
    documentName: '',
    document: null,
  },
];

export const profileData = {
  name: 'LKP Parduli Rasa Komputer',
  tagline: 'Tingkatkan Skill Komputer Anda Bersama Kami',
  logo: '',
  description: 'LKP Parduli Rasa Komputer adalah lembaga kursus dan pelatihan yang berdedikasi untuk meningkatkan keterampilan komputer masyarakat. Didirikan dengan semangat "Parduli Rasa" yang berarti kepedulian dari hati, kami berkomitmen untuk memberikan pendidikan komputer berkualitas dengan biaya yang terjangkau.',
  vision: 'Menjadi lembaga kursus komputer terdepan yang menghasilkan tenaga terampil dan berkompeten di bidang teknologi informasi.',
  mission: [
    'Menyelenggarakan program kursus komputer yang berkualitas dan relevan dengan kebutuhan industri',
    'Menyediakan fasilitas belajar yang modern dan nyaman',
    'Membina tenaga pengajar yang profesional dan berpengalaman',
    'Memberikan sertifikat kompetensi yang diakui secara nasional',
    'Menjalin kerjasama dengan dunia usaha dan industri'
  ],
  history: 'LKP Parduli Rasa Komputer didirikan pada tahun 2015 dengan tujuan mulia untuk mencerdaskan kehidupan bangsa melalui pendidikan komputer. Berawal dari ruang kecil dengan 10 unit komputer, kini LKP Parduli Rasa telah berkembang dengan fasilitas laboratorium yang modern dan telah meluluskan lebih dari 500 alumni yang berkarya di berbagai bidang.',
  address: 'Jl. Pendidikan No. 123, Kota Parduli, Provinsi Nusantara',
  phone: '(021) 1234-5678',
  email: 'info@lkppardulirasa.com',
  socialMedia: {
    facebook: 'https://facebook.com/lkppardulirasa',
    instagram: 'https://instagram.com/lkppardulirasa'
  }
};

export const stats = [
  { label: 'Alumni', value: 500, suffix: '+' },
  { label: 'Program Kursus', value: 6, suffix: '' },
  { label: 'Tahun Berdiri', value: 10, suffix: '+' },
  { label: 'Pengajar', value: 15, suffix: '+' }
];

export const accounts = [
  { id: 'acc-admin', username: 'admin', password: 'admin123', role: 'admin', name: 'Administrator', displayName: 'Administrator', email: 'admin@lkppardulirasa.com', status: 'active', permissions: ['*'], createdAt: '2025-01-01T08:00:00.000Z' },
  { id: 'acc-student-ahmad', username: 'ahmad', password: 'siswa123', role: 'student', name: 'Ahmad Fauzi', email: 'ahmad@email.com', studentId: 1, nis: 'PRK-2026-001', courseId: 1, enrollmentId: 'enr-2026-001', status: 'active', createdAt: '2026-01-05T08:00:00.000Z' },
  { id: 'acc-student-siti', username: 'siti', password: 'siswa123', role: 'student', name: 'Siti Nurhaliza', email: 'siti@email.com', studentId: 2, nis: 'PRK-2026-002', courseId: 2, enrollmentId: 'enr-2026-002', status: 'active', createdAt: '2026-01-12T08:00:00.000Z' },
  { id: 'acc-student-budi', username: 'budi', password: 'siswa123', role: 'student', name: 'Budi Santoso', email: 'budi@email.com', studentId: 3, nis: 'PRK-2026-003', courseId: 4, enrollmentId: 'enr-2025-003', status: 'active', createdAt: '2025-09-01T08:00:00.000Z' },
  { id: 'acc-student-dewi', username: 'dewi', password: 'siswa123', role: 'student', name: 'Dewi Lestari', email: 'dewi@email.com', studentId: 4, nis: 'PRK-2026-004', courseId: 5, enrollmentId: 'enr-2026-004', status: 'active', createdAt: '2026-03-01T08:00:00.000Z' },
  { id: 'acc-student-rudi', username: 'rudi', password: 'siswa123', role: 'student', name: 'Rudi Hermawan', email: 'rudi@email.com', studentId: 5, nis: 'PRK-2026-005', courseId: 6, enrollmentId: 'enr-2026-005', status: 'active', createdAt: '2026-03-05T08:00:00.000Z' },
  { id: 'acc-student-fitri', username: 'fitri', password: 'siswa123', role: 'student', name: 'Fitri Handayani', email: 'fitri@email.com', studentId: 6, nis: 'PRK-2026-006', courseId: 3, enrollmentId: 'enr-2025-006', status: 'active', createdAt: '2025-08-15T08:00:00.000Z' },
  { id: 'acc-student-andi', username: 'andi', password: 'siswa123', role: 'student', name: 'Andi Prasetyo', email: 'andi@email.com', studentId: 7, nis: 'PRK-2026-007', courseId: 1, enrollmentId: 'enr-2026-007', status: 'active', createdAt: '2026-03-10T08:00:00.000Z' },
  { id: 'acc-student-maya', username: 'maya', password: 'siswa123', role: 'student', name: 'Maya Sari', email: 'maya@email.com', studentId: 8, nis: 'PRK-2026-008', courseId: 4, enrollmentId: 'enr-2026-008', status: 'active', createdAt: '2026-02-10T08:00:00.000Z' },
];

export const enrollments = [
  { id: 'enr-2026-001', studentId: 1, courseId: 1, program: 'Microsoft Word', status: 'active', paymentStatus: 'verified', registrationDate: '2026-01-05', paymentDate: '2026-01-10', startedAt: '2026-01-12', currentModuleId: 'mod-1-4', progressPercent: 60 },
  { id: 'enr-2026-002', studentId: 2, courseId: 2, program: 'Microsoft Excel', status: 'active', paymentStatus: 'verified', registrationDate: '2026-01-12', paymentDate: '2026-01-15', startedAt: '2026-01-18', currentModuleId: 'mod-2-5', progressPercent: 80 },
  { id: 'enr-2025-003', studentId: 3, courseId: 4, program: 'Adobe Photoshop', status: 'completed', paymentStatus: 'verified', registrationDate: '2025-09-01', paymentDate: '2025-09-10', startedAt: '2025-09-12', completedAt: '2026-02-20', currentModuleId: 'mod-4-5', progressPercent: 100 },
  { id: 'enr-2026-004', studentId: 4, courseId: 5, program: 'Corel Draw', status: 'active', paymentStatus: 'pending', registrationDate: '2026-03-01', paymentDate: null, startedAt: '2026-03-03', currentModuleId: 'mod-5-2', progressPercent: 25 },
  { id: 'enr-2026-005', studentId: 5, courseId: 6, program: 'Auto CAD', status: 'active', paymentStatus: 'pending', registrationDate: '2026-03-05', paymentDate: null, startedAt: '2026-03-08', currentModuleId: 'mod-6-1', progressPercent: 15 },
  { id: 'enr-2025-006', studentId: 6, courseId: 3, program: 'Microsoft PowerPoint', status: 'completed', paymentStatus: 'verified', registrationDate: '2025-08-15', paymentDate: '2025-08-20', startedAt: '2025-08-22', completedAt: '2026-02-25', currentModuleId: 'mod-3-5', progressPercent: 100 },
  { id: 'enr-2026-007', studentId: 7, courseId: 1, program: 'Microsoft Word', status: 'active', paymentStatus: 'rejected', registrationDate: '2026-03-10', paymentDate: null, startedAt: '2026-03-12', currentModuleId: 'mod-1-1', progressPercent: 20 },
  { id: 'enr-2026-008', studentId: 8, courseId: 4, program: 'Adobe Photoshop', status: 'active', paymentStatus: 'verified', registrationDate: '2026-02-10', paymentDate: '2026-02-14', startedAt: '2026-02-16', currentModuleId: 'mod-4-4', progressPercent: 70 },
];

export const modules = [
  { id: 'mod-1-1', courseId: 1, order: 1, title: 'Pengenalan MS Word', summary: 'Mengenal antarmuka, ribbon, dan pengaturan dokumen dasar.', durationLabel: '1 Minggu' },
  { id: 'mod-1-2', courseId: 1, order: 2, title: 'Formatting Dokumen', summary: 'Belajar format paragraf, heading, dan layout halaman.', durationLabel: '1 Minggu' },
  { id: 'mod-1-3', courseId: 1, order: 3, title: 'Tabel & Grafik', summary: 'Menyusun tabel dan elemen visual sederhana di Word.', durationLabel: '1 Minggu' },
  { id: 'mod-1-4', courseId: 1, order: 4, title: 'Mail Merge', summary: 'Membuat surat massal dan label otomatis untuk kebutuhan administrasi.', durationLabel: '1 Minggu' },
  { id: 'mod-1-5', courseId: 1, order: 5, title: 'Cetak Massal', summary: 'Persiapan final dokumen dan pengaturan pencetakan profesional.', durationLabel: '1 Minggu' },
  { id: 'mod-2-1', courseId: 2, order: 1, title: 'Pengenalan MS Excel', summary: 'Pengenalan workbook, worksheet, dan format data dasar.', durationLabel: '1 Minggu' },
  { id: 'mod-2-2', courseId: 2, order: 2, title: 'Rumus & Fungsi', summary: 'Menggunakan fungsi dasar hingga logika sederhana untuk pengolahan data.', durationLabel: '1 Minggu' },
  { id: 'mod-2-3', courseId: 2, order: 3, title: 'Pivot Table', summary: 'Menyusun ringkasan data dan analisis cepat menggunakan Pivot Table.', durationLabel: '1 Minggu' },
  { id: 'mod-2-4', courseId: 2, order: 4, title: 'Chart & Grafik', summary: 'Membuat visualisasi data yang mudah dibaca untuk laporan kerja.', durationLabel: '1 Minggu' },
  { id: 'mod-2-5', courseId: 2, order: 5, title: 'Macro Dasar', summary: 'Automasi tugas berulang dengan perekaman macro sederhana.', durationLabel: '1 Minggu' },
  { id: 'mod-3-1', courseId: 3, order: 1, title: 'Pengenalan Slide', summary: 'Menata struktur presentasi dan layout slide yang efektif.', durationLabel: '1 Minggu' },
  { id: 'mod-3-2', courseId: 3, order: 2, title: 'Desain Template', summary: 'Membuat template presentasi yang konsisten dan profesional.', durationLabel: '1 Minggu' },
  { id: 'mod-3-3', courseId: 3, order: 3, title: 'Animasi & Transisi', summary: 'Mengatur transisi dan animasi yang mendukung storytelling.', durationLabel: '1 Minggu' },
  { id: 'mod-3-4', courseId: 3, order: 4, title: 'Multimedia', summary: 'Memasukkan audio, video, dan visual pendukung ke presentasi.', durationLabel: '1 Minggu' },
  { id: 'mod-3-5', courseId: 3, order: 5, title: 'Tips Presentasi', summary: 'Latihan penyampaian materi dan finalisasi deck untuk presentasi nyata.', durationLabel: '1 Minggu' },
  { id: 'mod-4-1', courseId: 4, order: 1, title: 'Pengenalan Photoshop', summary: 'Mengenal workspace dan tool utama untuk editing gambar.', durationLabel: '1 Minggu' },
  { id: 'mod-4-2', courseId: 4, order: 2, title: 'Layer & Masking', summary: 'Mengelola layer dan masking untuk komposisi yang rapi.', durationLabel: '1 Minggu' },
  { id: 'mod-4-3', courseId: 4, order: 3, title: 'Retouching Foto', summary: 'Melakukan koreksi warna dan perapihan visual foto.', durationLabel: '1 Minggu' },
  { id: 'mod-4-4', courseId: 4, order: 4, title: 'Desain Poster', summary: 'Menyusun komposisi poster promosi yang siap cetak.', durationLabel: '1 Minggu' },
  { id: 'mod-4-5', courseId: 4, order: 5, title: 'Manipulasi Gambar', summary: 'Mengerjakan proyek akhir manipulasi gambar kreatif.', durationLabel: '1 Minggu' },
  { id: 'mod-5-1', courseId: 5, order: 1, title: 'Pengenalan CorelDraw', summary: 'Mengenal canvas, object manager, dan workflow desain vektor.', durationLabel: '1 Minggu' },
  { id: 'mod-5-2', courseId: 5, order: 2, title: 'Desain Logo', summary: 'Membuat logo sederhana dengan prinsip bentuk dan warna.', durationLabel: '1 Minggu' },
  { id: 'mod-5-3', courseId: 5, order: 3, title: 'Layout Brosur', summary: 'Menyusun layout brosur dan materi cetak promosi.', durationLabel: '1 Minggu' },
  { id: 'mod-5-4', courseId: 5, order: 4, title: 'Desain Kemasan', summary: 'Merancang kemasan produk dengan ukuran dan grid yang akurat.', durationLabel: '1 Minggu' },
  { id: 'mod-5-5', courseId: 5, order: 5, title: 'Cetak & Export', summary: 'Menyiapkan file final untuk kebutuhan print dan digital.', durationLabel: '1 Minggu' },
  { id: 'mod-6-1', courseId: 6, order: 1, title: 'Pengenalan AutoCAD', summary: 'Mengenal interface, unit kerja, dan command dasar AutoCAD.', durationLabel: '1 Minggu' },
  { id: 'mod-6-2', courseId: 6, order: 2, title: 'Gambar 2D', summary: 'Membuat denah dan detail teknik 2D secara presisi.', durationLabel: '1 Minggu' },
  { id: 'mod-6-3', courseId: 6, order: 3, title: 'Gambar 3D', summary: 'Mengenal workflow pembuatan model 3D sederhana.', durationLabel: '1 Minggu' },
  { id: 'mod-6-4', courseId: 6, order: 4, title: 'Layout & Plotting', summary: 'Menyiapkan sheet layout dan hasil plotting untuk presentasi proyek.', durationLabel: '1 Minggu' },
  { id: 'mod-6-5', courseId: 6, order: 5, title: 'Proyek Akhir', summary: 'Menyusun gambar akhir dan presentasi proyek desain teknik.', durationLabel: '1 Minggu' },
];

export const assessmentProgress = [
  { id: 'asg-1-latihan', enrollmentId: 'enr-2026-001', studentId: 1, courseId: 1, type: 'latihan', status: 'passed', score: 88, maxScore: 100, notes: 'Latihan administrasi dokumen sudah rapi.', updatedAt: '2026-02-01T09:00:00.000Z' },
  { id: 'asg-1-teori', enrollmentId: 'enr-2026-001', studentId: 1, courseId: 1, type: 'teori', status: 'in_review', score: 76, maxScore: 100, notes: 'Jawaban teori sedang direview admin.', updatedAt: '2026-02-07T11:30:00.000Z' },
  { id: 'asg-1-praktik', enrollmentId: 'enr-2026-001', studentId: 1, courseId: 1, type: 'praktik', status: 'not_started', score: null, maxScore: 100, notes: '', updatedAt: '2026-02-07T11:30:00.000Z' },
  { id: 'asg-2-latihan', enrollmentId: 'enr-2026-002', studentId: 2, courseId: 2, type: 'latihan', status: 'passed', score: 92, maxScore: 100, notes: 'Latihan pivot dan formula sudah konsisten.', updatedAt: '2026-02-06T09:00:00.000Z' },
  { id: 'asg-2-teori', enrollmentId: 'enr-2026-002', studentId: 2, courseId: 2, type: 'teori', status: 'passed', score: 89, maxScore: 100, notes: 'Teori dinyatakan lulus.', updatedAt: '2026-02-09T09:00:00.000Z' },
  { id: 'asg-2-praktik', enrollmentId: 'enr-2026-002', studentId: 2, courseId: 2, type: 'praktik', status: 'in_progress', score: null, maxScore: 100, notes: 'Menunggu presentasi hasil praktik.', updatedAt: '2026-02-12T09:00:00.000Z' },
  { id: 'asg-3-latihan', enrollmentId: 'enr-2025-003', studentId: 3, courseId: 4, type: 'latihan', status: 'passed', score: 90, maxScore: 100, notes: 'Seluruh latihan mandiri tuntas.', updatedAt: '2026-01-20T09:00:00.000Z' },
  { id: 'asg-3-teori', enrollmentId: 'enr-2025-003', studentId: 3, courseId: 4, type: 'teori', status: 'passed', score: 87, maxScore: 100, notes: 'Nilai teori memenuhi syarat.', updatedAt: '2026-01-25T09:00:00.000Z' },
  { id: 'asg-3-praktik', enrollmentId: 'enr-2025-003', studentId: 3, courseId: 4, type: 'praktik', status: 'passed', score: 93, maxScore: 100, notes: 'Praktik proyek akhir sangat baik.', updatedAt: '2026-02-10T09:00:00.000Z' },
  { id: 'asg-4-latihan', enrollmentId: 'enr-2026-004', studentId: 4, courseId: 5, type: 'latihan', status: 'passed', score: 80, maxScore: 100, notes: 'Latihan desain logo selesai.', updatedAt: '2026-03-08T09:00:00.000Z' },
  { id: 'asg-4-teori', enrollmentId: 'enr-2026-004', studentId: 4, courseId: 5, type: 'teori', status: 'not_started', score: null, maxScore: 100, notes: '', updatedAt: '2026-03-08T09:00:00.000Z' },
  { id: 'asg-4-praktik', enrollmentId: 'enr-2026-004', studentId: 4, courseId: 5, type: 'praktik', status: 'not_started', score: null, maxScore: 100, notes: '', updatedAt: '2026-03-08T09:00:00.000Z' },
  { id: 'asg-5-latihan', enrollmentId: 'enr-2026-005', studentId: 5, courseId: 6, type: 'latihan', status: 'in_progress', score: null, maxScore: 100, notes: 'Masih tahap pengenalan AutoCAD.', updatedAt: '2026-03-10T09:00:00.000Z' },
  { id: 'asg-5-teori', enrollmentId: 'enr-2026-005', studentId: 5, courseId: 6, type: 'teori', status: 'not_started', score: null, maxScore: 100, notes: '', updatedAt: '2026-03-10T09:00:00.000Z' },
  { id: 'asg-5-praktik', enrollmentId: 'enr-2026-005', studentId: 5, courseId: 6, type: 'praktik', status: 'not_started', score: null, maxScore: 100, notes: '', updatedAt: '2026-03-10T09:00:00.000Z' },
  { id: 'asg-6-latihan', enrollmentId: 'enr-2025-006', studentId: 6, courseId: 3, type: 'latihan', status: 'passed', score: 88, maxScore: 100, notes: 'Latihan presentasi lengkap.', updatedAt: '2026-01-18T09:00:00.000Z' },
  { id: 'asg-6-teori', enrollmentId: 'enr-2025-006', studentId: 6, courseId: 3, type: 'teori', status: 'passed', score: 91, maxScore: 100, notes: 'Teori presentasi lulus.', updatedAt: '2026-01-22T09:00:00.000Z' },
  { id: 'asg-6-praktik', enrollmentId: 'enr-2025-006', studentId: 6, courseId: 3, type: 'praktik', status: 'passed', score: 94, maxScore: 100, notes: 'Praktik final sangat baik.', updatedAt: '2026-02-05T09:00:00.000Z' },
  { id: 'asg-7-latihan', enrollmentId: 'enr-2026-007', studentId: 7, courseId: 1, type: 'latihan', status: 'not_started', score: null, maxScore: 100, notes: 'Akses penuh tertahan karena pembayaran bermasalah.', updatedAt: '2026-03-12T09:00:00.000Z' },
  { id: 'asg-7-teori', enrollmentId: 'enr-2026-007', studentId: 7, courseId: 1, type: 'teori', status: 'not_started', score: null, maxScore: 100, notes: '', updatedAt: '2026-03-12T09:00:00.000Z' },
  { id: 'asg-7-praktik', enrollmentId: 'enr-2026-007', studentId: 7, courseId: 1, type: 'praktik', status: 'not_started', score: null, maxScore: 100, notes: '', updatedAt: '2026-03-12T09:00:00.000Z' },
  { id: 'asg-8-latihan', enrollmentId: 'enr-2026-008', studentId: 8, courseId: 4, type: 'latihan', status: 'passed', score: 90, maxScore: 100, notes: 'Latihan retouching dan poster selesai.', updatedAt: '2026-03-07T09:00:00.000Z' },
  { id: 'asg-8-teori', enrollmentId: 'enr-2026-008', studentId: 8, courseId: 4, type: 'teori', status: 'passed', score: 88, maxScore: 100, notes: 'Teori dinyatakan lulus.', updatedAt: '2026-03-10T09:00:00.000Z' },
  { id: 'asg-8-praktik', enrollmentId: 'enr-2026-008', studentId: 8, courseId: 4, type: 'praktik', status: 'in_review', score: 86, maxScore: 100, notes: 'Menunggu final review proyek manipulasi gambar.', updatedAt: '2026-03-14T09:00:00.000Z' },
];

export const assessmentDefinitions = [
  {
    id: 'def-1-latihan',
    courseId: 1,
    type: 'latihan',
    title: 'Latihan Dokumen Administrasi Word',
    description: 'Latihan mandiri untuk memastikan siswa mampu menyiapkan dokumen administrasi yang rapi dan konsisten.',
    instructions: [
      'Gunakan format heading, tabel, dan numbering yang konsisten.',
      'Pastikan dokumen mudah dibaca dan siap dicetak.',
    ],
    durationMinutes: 45,
    passingScore: 75,
    maxAttempts: 3,
    questionShuffle: false,
    allowRetry: true,
    isPublished: true,
    moduleIds: ['mod-1-1', 'mod-1-2', 'mod-1-3'],
    questions: [
      {
        id: 'def-1-latihan-q1',
        kind: 'multiple_choice',
        prompt: 'Fitur Word mana yang paling tepat untuk membuat surat massal otomatis?',
        options: [
          { id: 'a', label: 'Track Changes', value: 'track_changes' },
          { id: 'b', label: 'Mail Merge', value: 'mail_merge' },
          { id: 'c', label: 'SmartArt', value: 'smart_art' },
        ],
        answer: 'mail_merge',
      },
      {
        id: 'def-1-latihan-q2',
        kind: 'essay',
        prompt: 'Jelaskan langkah singkat menyiapkan format paragraf untuk surat resmi.',
      },
      {
        id: 'def-1-latihan-q3',
        kind: 'essay',
        prompt: 'Unggah ringkasan praktik format tabel yang sudah kamu kerjakan.',
      },
    ],
    createdAt: '2026-01-20T08:00:00.000Z',
    updatedAt: '2026-02-01T09:00:00.000Z',
  },
  {
    id: 'def-1-teori',
    courseId: 1,
    type: 'teori',
    title: 'Ujian Teori Microsoft Word',
    description: 'Evaluasi konsep dasar sampai menengah terkait fitur dokumen profesional di Microsoft Word.',
    instructions: [
      'Kerjakan seluruh soal teori tanpa bantuan catatan.',
      'Jawaban essay harus ringkas dan menjelaskan alasan.',
    ],
    durationMinutes: 60,
    passingScore: 75,
    maxAttempts: 1,
    questionShuffle: true,
    allowRetry: false,
    isPublished: true,
    moduleIds: ['mod-1-1', 'mod-1-2', 'mod-1-3', 'mod-1-4'],
    questions: [
      {
        id: 'def-1-teori-q1',
        kind: 'multiple_choice',
        prompt: 'Shortcut yang umum dipakai untuk menyimpan dokumen adalah...',
        options: [
          { id: 'a', label: 'Ctrl + P', value: 'ctrl_p' },
          { id: 'b', label: 'Ctrl + S', value: 'ctrl_s' },
          { id: 'c', label: 'Ctrl + D', value: 'ctrl_d' },
        ],
        answer: 'ctrl_s',
      },
      {
        id: 'def-1-teori-q2',
        kind: 'multiple_choice',
        prompt: 'Fitur untuk menggabungkan data nama penerima dengan template surat disebut...',
        options: [
          { id: 'a', label: 'Mail Merge', value: 'mail_merge' },
          { id: 'b', label: 'Style Set', value: 'style_set' },
          { id: 'c', label: 'Page Break', value: 'page_break' },
        ],
        answer: 'mail_merge',
      },
      {
        id: 'def-1-teori-q3',
        kind: 'essay',
        prompt: 'Apa manfaat penggunaan styles pada dokumen panjang?',
      },
    ],
    createdAt: '2026-01-25T08:00:00.000Z',
    updatedAt: '2026-02-07T11:30:00.000Z',
  },
  {
    id: 'def-1-praktik',
    courseId: 1,
    type: 'praktik',
    title: 'Ujian Praktik Penyusunan Dokumen Word',
    description: 'Siswa diminta membuat dokumen siap cetak dengan standar format administrasi kantor.',
    instructions: [
      'Buat satu dokumen final lengkap dengan header, tabel, dan mail merge sederhana.',
      'Gunakan template yang sudah dipelajari selama kelas berlangsung.',
    ],
    durationMinutes: 90,
    passingScore: 80,
    maxAttempts: 1,
    questionShuffle: false,
    allowRetry: true,
    isPublished: true,
    moduleIds: ['mod-1-4', 'mod-1-5'],
    questions: [
      {
        id: 'def-1-praktik-q1',
        kind: 'essay',
        prompt: 'Unggah hasil dokumen final beserta catatan proses pengerjaan.',
      },
      {
        id: 'def-1-praktik-q2',
        kind: 'essay',
        prompt: 'Jelaskan bagian paling menantang saat menyiapkan layout dokumen.',
      },
    ],
    createdAt: '2026-02-01T08:00:00.000Z',
    updatedAt: '2026-02-07T11:30:00.000Z',
  },
];

export const assessmentSubmissions = [
  {
    id: 'sub-1-latihan-1',
    definitionId: 'def-1-latihan',
    enrollmentId: 'enr-2026-001',
    studentId: 1,
    courseId: 1,
    type: 'latihan',
    title: 'Latihan Dokumen Ahmad Fauzi',
    status: 'reviewed',
    attempt: 1,
    score: 88,
    maxScore: 100,
    submittedAt: '2026-02-01T08:45:00.000Z',
    reviewedAt: '2026-02-01T09:00:00.000Z',
    reviewerName: 'Admin LKP',
    notes: 'Dokumen sudah rapi dan struktur heading konsisten.',
    answers: [
      { questionId: 'def-1-latihan-q1', value: 'mail_merge' },
      { questionId: 'def-1-latihan-q2', value: 'Mengatur style heading, margin, dan spacing agar surat resmi mudah dibaca.' },
      { questionId: 'def-1-latihan-q3', value: 'Latihan tabel surat keluar dan daftar penerima selesai dikerjakan.' },
    ],
    attachments: [],
    createdAt: '2026-02-01T08:45:00.000Z',
    updatedAt: '2026-02-01T09:00:00.000Z',
  },
  {
    id: 'sub-1-teori-1',
    definitionId: 'def-1-teori',
    enrollmentId: 'enr-2026-001',
    studentId: 1,
    courseId: 1,
    type: 'teori',
    title: 'Ujian Teori Ahmad Fauzi',
    status: 'submitted',
    attempt: 1,
    score: 76,
    maxScore: 100,
    submittedAt: '2026-02-07T10:50:00.000Z',
    reviewedAt: null,
    reviewerName: '',
    notes: 'Menunggu validasi jawaban essay dari admin.',
    answers: [
      { questionId: 'def-1-teori-q1', value: 'ctrl_s' },
      { questionId: 'def-1-teori-q2', value: 'mail_merge' },
      { questionId: 'def-1-teori-q3', value: 'Styles membantu konsistensi format dan mempermudah pembuatan daftar isi.' },
    ],
    attachments: [],
    createdAt: '2026-02-07T10:50:00.000Z',
    updatedAt: '2026-02-07T11:30:00.000Z',
  },
  {
    id: 'sub-2-praktik-1',
    enrollmentId: 'enr-2026-002',
    studentId: 2,
    courseId: 2,
    type: 'praktik',
    title: 'Praktik Dashboard Excel Siti Nurhaliza',
    status: 'draft',
    attempt: 1,
    score: null,
    maxScore: 100,
    submittedAt: '2026-02-12T08:45:00.000Z',
    reviewedAt: null,
    reviewerName: '',
    notes: 'Masih melengkapi file praktik untuk presentasi final.',
    answers: [],
    attachments: [],
    createdAt: '2026-02-12T08:45:00.000Z',
    updatedAt: '2026-02-12T09:00:00.000Z',
  },
  {
    id: 'sub-3-praktik-1',
    enrollmentId: 'enr-2025-003',
    studentId: 3,
    courseId: 4,
    type: 'praktik',
    title: 'Praktik Proyek Akhir Budi Santoso',
    status: 'reviewed',
    attempt: 1,
    score: 93,
    maxScore: 100,
    submittedAt: '2026-02-10T08:30:00.000Z',
    reviewedAt: '2026-02-10T09:00:00.000Z',
    reviewerName: 'Admin LKP',
    notes: 'Komposisi visual kuat dan hasil akhir sangat rapi.',
    answers: [],
    attachments: [],
    createdAt: '2026-02-10T08:30:00.000Z',
    updatedAt: '2026-02-10T09:00:00.000Z',
  },
  {
    id: 'sub-8-praktik-1',
    enrollmentId: 'enr-2026-008',
    studentId: 8,
    courseId: 4,
    type: 'praktik',
    title: 'Praktik Manipulasi Gambar Maya Sari',
    status: 'submitted',
    attempt: 1,
    score: 86,
    maxScore: 100,
    submittedAt: '2026-03-14T08:15:00.000Z',
    reviewedAt: null,
    reviewerName: '',
    notes: 'Menunggu final review proyek akhir.',
    answers: [],
    attachments: [],
    createdAt: '2026-03-14T08:15:00.000Z',
    updatedAt: '2026-03-14T09:00:00.000Z',
  },
];

export const classroomPosts = [
  {
    id: 'post-1-1',
    courseId: 1,
    title: 'Pengumuman Fokus Mail Merge',
    body: 'Pertemuan minggu ini berfokus pada simulasi surat massal dan pengecekan layout dokumen final.',
    authorName: 'Admin LKP',
    status: 'published',
    publishedAt: '2026-02-05T08:00:00.000Z',
    createdAt: '2026-02-05T08:00:00.000Z',
    updatedAt: '2026-02-05T08:00:00.000Z',
  },
  {
    id: 'post-2-1',
    courseId: 2,
    title: 'Reminder Presentasi Pivot Table',
    body: 'Siswa Excel diminta membawa file latihan pivot table dan dashboard sederhana untuk review kelas.',
    authorName: 'Admin LKP',
    status: 'published',
    publishedAt: '2026-02-08T08:00:00.000Z',
    createdAt: '2026-02-08T08:00:00.000Z',
    updatedAt: '2026-02-08T08:00:00.000Z',
  },
  {
    id: 'post-4-1',
    courseId: 4,
    title: 'Review Proyek Poster',
    body: 'Kelas Photoshop akan memakai sesi lab tambahan untuk final review poster dan manipulasi gambar.',
    authorName: 'Admin LKP',
    status: 'published',
    publishedAt: '2026-03-09T08:00:00.000Z',
    createdAt: '2026-03-09T08:00:00.000Z',
    updatedAt: '2026-03-09T08:00:00.000Z',
  },
];

export const classworkItems = [
  {
    id: 'cwi-1-assignment-1',
    courseId: 1,
    topicId: 'mod-1-4',
    type: 'assignment',
    title: 'Tugas Draft Surat Massal',
    summary: 'Susun draft surat massal lengkap dengan data penerima dan format final siap cetak.',
    instructions: 'Unggah dokumen Word final dan ringkasan langkah yang dipakai saat mengatur mail merge.',
    maxScore: 100,
    passingScore: 75,
    maxAttempts: 1,
    dueAt: '2026-02-10T09:00:00.000Z',
    orderIndex: 1,
    isPublished: true,
    createdAt: '2026-02-04T08:00:00.000Z',
    updatedAt: '2026-02-04T08:00:00.000Z',
  },
  {
    id: 'cwi-1-question-1',
    courseId: 1,
    topicId: 'mod-1-2',
    type: 'question',
    title: 'Refleksi Format Paragraf',
    summary: 'Jawab singkat apa tantangan terbesar saat merapikan format paragraf.',
    instructions: 'Tulis refleksi singkat 1-2 paragraf.',
    maxScore: 20,
    maxAttempts: 1,
    orderIndex: 2,
    isPublished: true,
    createdAt: '2026-01-28T08:00:00.000Z',
    updatedAt: '2026-01-28T08:00:00.000Z',
  },
  {
    id: 'cwi-2-quiz-1',
    courseId: 2,
    topicId: 'mod-2-3',
    type: 'quiz_assignment',
    title: 'Quiz Pivot Table',
    summary: 'Quiz singkat untuk mengecek pemahaman penyusunan ringkasan data dan field layout.',
    instructions: 'Kerjakan seluruh soal quiz sebelum sesi review.',
    maxScore: 100,
    passingScore: 75,
    maxAttempts: 2,
    orderIndex: 1,
    isPublished: true,
    questions: [
      {
        id: 'cwi-2-quiz-1-q1',
        kind: 'multiple_choice',
        prompt: 'Field mana yang paling tepat ditempatkan di area Values saat menghitung total penjualan?',
        options: [
          { id: 'a', label: 'Nomor Telepon', value: 'phone' },
          { id: 'b', label: 'Total Penjualan', value: 'sales_total' },
          { id: 'c', label: 'Alamat', value: 'address' },
        ],
        answer: 'sales_total',
      },
    ],
    createdAt: '2026-02-06T08:00:00.000Z',
    updatedAt: '2026-02-06T08:00:00.000Z',
  },
  {
    id: 'cwi-4-assignment-1',
    courseId: 4,
    topicId: 'mod-4-4',
    type: 'assignment',
    title: 'Poster Promosi Kelas',
    summary: 'Buat poster promosi kursus dengan layout, tipografi, dan visual yang siap presentasi.',
    instructions: 'Unggah file poster final dan jelaskan konsep visual yang dipilih.',
    maxScore: 100,
    passingScore: 78,
    maxAttempts: 1,
    dueAt: '2026-03-12T09:00:00.000Z',
    orderIndex: 1,
    isPublished: true,
    createdAt: '2026-03-05T08:00:00.000Z',
    updatedAt: '2026-03-05T08:00:00.000Z',
  },
];

export const classworkResults = [
  {
    id: 'cwr-1-assignment-1',
    itemId: 'cwi-1-assignment-1',
    enrollmentId: 'enr-2026-001',
    studentId: 1,
    courseId: 1,
    status: 'passed',
    score: 90,
    maxScore: 100,
    feedback: 'Struktur surat dan data penerima sudah konsisten.',
    submittedAt: '2026-02-10T08:30:00.000Z',
    completedAt: '2026-02-10T09:00:00.000Z',
    createdAt: '2026-02-10T08:30:00.000Z',
    updatedAt: '2026-02-10T09:00:00.000Z',
  },
  {
    id: 'cwr-1-question-1',
    itemId: 'cwi-1-question-1',
    enrollmentId: 'enr-2026-001',
    studentId: 1,
    courseId: 1,
    status: 'in_review',
    score: 18,
    maxScore: 20,
    feedback: 'Menunggu validasi refleksi singkat.',
    submittedAt: '2026-01-30T08:30:00.000Z',
    createdAt: '2026-01-30T08:30:00.000Z',
    updatedAt: '2026-01-30T09:00:00.000Z',
  },
  {
    id: 'cwr-2-quiz-1',
    itemId: 'cwi-2-quiz-1',
    enrollmentId: 'enr-2026-002',
    studentId: 2,
    courseId: 2,
    status: 'passed',
    score: 94,
    maxScore: 100,
    feedback: 'Pemahaman pivot table sangat baik.',
    submittedAt: '2026-02-07T08:20:00.000Z',
    completedAt: '2026-02-07T08:45:00.000Z',
    createdAt: '2026-02-07T08:20:00.000Z',
    updatedAt: '2026-02-07T08:45:00.000Z',
  },
  {
    id: 'cwr-8-assignment-1',
    itemId: 'cwi-4-assignment-1',
    enrollmentId: 'enr-2026-008',
    studentId: 8,
    courseId: 4,
    status: 'in_review',
    score: 87,
    maxScore: 100,
    feedback: 'Final review poster menunggu catatan terakhir instruktur.',
    submittedAt: '2026-03-12T08:15:00.000Z',
    createdAt: '2026-03-12T08:15:00.000Z',
    updatedAt: '2026-03-12T09:00:00.000Z',
  },
];

export const classworkSubmissions = [
  {
    id: 'cws-1-assignment-1',
    itemId: 'cwi-1-assignment-1',
    enrollmentId: 'enr-2026-001',
    studentId: 1,
    courseId: 1,
    status: 'reviewed',
    attempt: 1,
    score: 90,
    maxScore: 100,
    feedback: 'Dokumen final siap cetak dan data mail merge rapi.',
    reviewerName: 'Admin LKP',
    submittedAt: '2026-02-10T08:30:00.000Z',
    reviewedAt: '2026-02-10T09:00:00.000Z',
    answers: [],
    attachments: [],
    createdAt: '2026-02-10T08:30:00.000Z',
    updatedAt: '2026-02-10T09:00:00.000Z',
  },
  {
    id: 'cws-1-question-1',
    itemId: 'cwi-1-question-1',
    enrollmentId: 'enr-2026-001',
    studentId: 1,
    courseId: 1,
    status: 'submitted',
    attempt: 1,
    score: 18,
    maxScore: 20,
    feedback: 'Menunggu review jawaban refleksi.',
    submittedAt: '2026-01-30T08:30:00.000Z',
    answers: [
      {
        questionId: 'cwi-1-question-1-q1',
        value: 'Menjaga konsistensi spacing dan heading jadi bagian yang paling perlu dicek ulang.',
      },
    ],
    attachments: [],
    createdAt: '2026-01-30T08:30:00.000Z',
    updatedAt: '2026-01-30T09:00:00.000Z',
  },
  {
    id: 'cws-2-quiz-1',
    itemId: 'cwi-2-quiz-1',
    enrollmentId: 'enr-2026-002',
    studentId: 2,
    courseId: 2,
    status: 'reviewed',
    attempt: 1,
    score: 94,
    maxScore: 100,
    feedback: 'Jawaban quiz sudah akurat dan cepat.',
    reviewerName: 'Admin LKP',
    submittedAt: '2026-02-07T08:20:00.000Z',
    reviewedAt: '2026-02-07T08:45:00.000Z',
    answers: [
      { questionId: 'cwi-2-quiz-1-q1', value: 'sales_total' },
    ],
    attachments: [],
    createdAt: '2026-02-07T08:20:00.000Z',
    updatedAt: '2026-02-07T08:45:00.000Z',
  },
  {
    id: 'cws-8-assignment-1',
    itemId: 'cwi-4-assignment-1',
    enrollmentId: 'enr-2026-008',
    studentId: 8,
    courseId: 4,
    status: 'submitted',
    attempt: 1,
    score: 87,
    maxScore: 100,
    feedback: 'Poster sudah masuk antrian review akhir.',
    submittedAt: '2026-03-12T08:15:00.000Z',
    answers: [],
    attachments: [],
    createdAt: '2026-03-12T08:15:00.000Z',
    updatedAt: '2026-03-12T09:00:00.000Z',
  },
];

// Mock user for login simulation
export const mockUsers = [
  { id: 1, username: 'admin', password: 'admin123', role: 'admin', name: 'Administrator', accountId: 'acc-admin', email: 'admin@lkppardulirasa.com' },
  { id: 2, username: 'ahmad', password: 'siswa123', role: 'student', name: 'Ahmad Fauzi', nis: 'PRK-2026-001', studentId: 1, courseId: 1, enrollmentId: 'enr-2026-001', accountId: 'acc-student-ahmad' },
  { id: 3, username: 'siti', password: 'siswa123', role: 'student', name: 'Siti Nurhaliza', nis: 'PRK-2026-002', studentId: 2, courseId: 2, enrollmentId: 'enr-2026-002', accountId: 'acc-student-siti' },
  { id: 4, username: 'budi', password: 'siswa123', role: 'student', name: 'Budi Santoso', nis: 'PRK-2026-003', studentId: 3, courseId: 4, enrollmentId: 'enr-2025-003', accountId: 'acc-student-budi' },
];
